### ISSUE TITLE
'Access-Control-Allow-Origin' header is missing

### ISSUE THREAD

**Issue by mohayman2008** [stefanbohacek/HelloSalut#1]
The response doesn't contain the 'Access-Control-Allow-Origin' header so browser refuses to use the response fetched through AJAX or fetch API.

#Request

GET /?lang=fr HTTP/2
Host: hellosalut.stefanbohacek.dev
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: null
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site

#Response

HTTP/2 200 OK
server: nginx
date: Tue, 21 Feb 2023 04:52:15 GMT
content-type: application/json
content-length: 29
x-powered-by: PHP/8.2.1
X-Firefox-Spdy: h2

##Console##
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hellosalut.stefanbohacek.dev/?lang=fr. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

**Comment by stefanbohacek** [comment]
Hi @mohayman2008, thank you for reporting this issue. The missing header was added, can you please try again?

**Comment by mohayman2008** [comment]
Yes it's working now, Thank you

**Comment by stefanbohacek** [comment]
No problem!
